import mongoose from "mongoose";

/**
 * Case schema representing a legal case within the system.
 * Defines case metadata, role-based relationships,
 * lifecycle status, and historical notes.
 */
const caseSchema = new mongoose.Schema(
    {
        // Unique, human-readable case identifier
        caseNumber: {
            type: String,
            required: true,
            unique: true
        },

        // Short descriptive title of the case
        title: {
            type: String,
            required: true,
            trim: true
        },

        // Detailed case description or summary
        description: {
            type: String,
            required: true,
            trim: true
        },

        /**
  * AI-inferred legal specialization
  *
  * Used for:
  * - Advocate matching
  * - Analytics
  * - Case insights
  */
        specialization: {
            type: String,
            enum: [
                "Civil",
                "Criminal",
                "Family",
                "Property",
                "Corporate",
                "Consumer Protection",
                "Labour",
                "Intellectual Property",
                "Tax",
                "Personal Injury",
                "Other"
            ],
            required: true
        },

        /**
         * AI Case Analysis Snapshot
         *
         * Stores structured output generated by the
         * AI Case Assistant at the time of case creation.
         * This ensures transparency and auditability.
         */
        aiAnalysis: {
            urgency: {
                type: String,
                enum: ["Immediate", "Soon", "Exploratory"]
            },

            evidenceReadiness: {
                type: String,
                enum: ["Low", "Medium", "High"]
            },

            recommendedSpecialization: {
                type: String
            },

            suggestedNextSteps: [
                {
                    type: String
                }
            ],

            provider: {
                type: String,
                default: "AI Case Assistant"
            },

            analyzedAt: {
                type: Date,
                default: Date.now
            }
        },


        // Current lifecycle status of the case
        status: {
            type: String,
            enum: ["open", "in_progress", "closed"],
            default: "open"
        },

        /**
         * Relationship mappings
         */

        appointment: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "Appointment",
            unique: true,
            required: true
        },

        // Client associated with the case
        client: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true
        },

        // Primary advocate assigned to the case
        advocate: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true
        },

        // Junior advocates assisting on the case
        assignedJuniors: [
            {
                type: mongoose.Schema.Types.ObjectId,
                ref: "User"
            }
        ],

        // User who created or registered the case in the system
        createdBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true
        },

        /**
         * Case activity log / history
         */

        // Chronological list of notes or updates related to the case
        caseHistory: [
            {
                // Case note or update content
                note: {
                    type: String,
                    required: true
                },

                // User who added the note
                addedBy: {
                    type: mongoose.Schema.Types.ObjectId,
                    ref: "User",
                    required: true
                },

                // Timestamp for when the note was created
                createdAt: {
                    type: Date,
                    default: Date.now
                }
            }
        ],

        // Timestamp marking when the case was officially opened
        openedAt: {
            type: Date,
            default: Date.now
        },

        // Timestamp marking when the case was closed
        closedAt: {
            type: Date
        }
    },
    {
        // Automatically maintains createdAt and updatedAt fields
        timestamps: true
    }
);

// Export Case model for use in case management workflows
export default mongoose.model("Case", caseSchema);
